name: CI Failure Advisor

on:
  workflow_run:
    workflows: [test]
    types: [completed]

jobs:
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22' 
          
      - name: Install Codex CLI
        run: |
          sudo npm install -g @openai/codex@0.1.2505172129

      - name: Install dependencies
        run: |
          sudo apt install git

      - name: Generate PR summary issue
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          failedRunId=${{ github.event.workflow_run.id }}
          ciLog=$(gh run view $failedRunId --log-failed)
          echo $ciLog | head -2