name: Monthly Codex CI

on:
  push:
    branches: [ master ]
  schedule:
    # Runs at 00:00 UTC on the first day of each month
    - cron: '45 6 1 * *'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22' 
          
      - name: Install Codex CLI
        run: |
          sudo npm install -g @openai/codex@0.1.2505172129

      - name: Generate commit summary issue
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_KEY }}
          CODEX_QUIET_MODE: 1
          GH_TOKEN: ${{ github.token }}
        run: |
          # Create a file listing all commits in the last month
          codex --version
          codex -a auto-edit -q \
            "create ISSUE_BODY.md listing all commits since one month ago in markdown format"
          # Open a GitHub issue with that body
          gh issue create \
            --title "Monthly Commits for $(date '+%B %Y')" \
            --body-file ISSUE_BODY.md

      - name: Update CHANGELOG
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_KEY }}
          CODEX_QUIET_MODE: 1
        run: |
          codex -a auto-edit -q \
            "update CHANGELOG.md by adding a new section for $(date '+%B %Y') summarizing commits from the last month"

      - name: Commit CHANGELOG updates
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          # git add CHANGELOG.md
          # git commit -m "docs: update CHANGELOG for $(date '+%B %Y')" || echo "No changes to commit"

      - name: Bump version info
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_KEY }}
          CODEX_QUIET_MODE: 1
        run: |
          codex -a auto-edit -q \
            "Update version information in the following files for next release:
            1. debian/control: Standards-Version
            2. docs/source/conf.py: release
            3. quark/__init__.py: __version__
            Where YY.MM.X stands for:
             - YY: last two digits of the year
             - MM: month number
             - X: release count within that month (normally 1)
            For example, 25.2.1 means the 1st release in February 2025."
      
      - name: Create pull request for version bump
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: bump version for next release"
          title: "chore: bump version and update CHANGELOG for $(date '+%B %Y')"
          body: |
            This PR updates the version information and CHANGELOG for the upcoming release.
